# Generated by Django 5.2.7 on 2025-11-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commets',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
