# Generated by Django 5.2.7 on 2025-11-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0002_commets_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='commets',
            name='signature',
            field=models.CharField(default='Firma', max_length=100),
        ),
    ]
