# Generated by Django 5.2.7 on 2025-11-15 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0003_commets_signature'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='commets',
            new_name='Commet',
        ),
    ]
