# Generated by Django 5.2.7 on 2025-11-15 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0004_rename_commets_commet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commet',
            new_name='Comment',
        ),
    ]
